### ISSUE TITLE
Color Palette Choices

### ISSUE THREAD

**Issue by fajalar** [refreshpdx/website#10]
Post 'em if you got 'em!

**Comment by susanjrobertson** [comment]
I like Blue and Orange as ideas for colors. Blue because we get rain and orange is the complement and makes a nice pop.

**Comment by fajalar** [comment]
http://www.colourlovers.com/palette/4309335/rfrsh2017

http://www.colourlovers.com/palette/4309340/rfrsh2017-1

**Comment by susanjrobertson** [comment]
I vote for the second one that @matto linked to.

**Comment by fajalar** [comment]
done and done.
