### ISSUE TITLE
Font Choices

### ISSUE THREAD

**Issue by fajalar** [refreshpdx/website#11]
Pick 2 complimentary fonts.

1 for headings.
1 for body.

**Comment by susanjrobertson** [comment]
I like the idea of main body font being a system font. Helvetica maybe?

**Comment by susanjrobertson** [comment]
Opinions on these @kitt or @dalla777 for headline? Look at Google fonts to see them:

- Roboto Slab is @fajalar's vote
- Merriweather (I like, @fajalar hates the y)

**Comment by susanjrobertson** [comment]
I'm find with Roboto Slab for our fancy headline font.

**Comment by fajalar** [comment]
Roboto Slab for headings
Helvetica as body.

done and done.
