### ISSUE TITLE
Is Eventbrite the right tool for us?

### ISSUE THREAD

**Issue by susanjrobertson** [refreshpdx/website#19]
We currently use Eventbrite for ticketing/tracking attendees for our events. Is it still the right tool for us? Do we need to track numbers? Should we use something else?

**Comment by susanjrobertson** [comment]
I've been thinking about this and it gives us a list for the giveaways, so that's a good thing. I hate meet up, but it does seem to be the place people go, but I don't want to pay for it, which I think we'd have to. So I'd stick with EB for now, only switching if we get sponsorship and can pay for meet up that way.

**Comment by fajalar** [comment]
Agree.
