### ISSUE TITLE
To Sass or not to Sass?

### ISSUE THREAD

**Issue by susanjrobertson** [refreshpdx/website#20]
Do we have the ability to compile Sass? Should we use it? What say you @dalla777, @kitt, or @fajalar?

**Comment by fajalar** [comment]
Will our site ever be so complex as to need compiled css? 

Yes, you may know my ability to understand the question with the above sentence.

**Comment by susanjrobertson** [comment]
I think for variables for colors it is nice, but it's not absolutely necessary, just thought I would ask.

**Comment by dalla777** [comment]
I would prefer to Sass. I have a pretty basic Gulpfile we can use, or if someone has another process they prefer, I'm not particular in that regard.

**Comment by susanjrobertson** [comment]
I would ask @kitt about the best way to implement, since she did the whole vagrant deal, I don't want to mess anything up. But gulp is fine with me.

**Comment by susanjrobertson** [comment]
With #21 we've decided and are doing it.
